<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>markdown</string>
		<string>md</string>
		<string>html</string>
	</array>
	<key>firstLineMatch</key>
	<string>---</string>
	<key>name</key>
	<string>Jekyll</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(---[ ]*\n)</string>
			<key>end</key>
			<string>(---[ ]*\n)</string>
			<key>name</key>
			<string>source.yaml.header.markdown.jekyll</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{% +highlight +(js)( +linenos)? +%\}</string>
			<key>end</key>
			<string>\{% +endhighlight +%\}\n</string>
			<key>name</key>
			<string>source.$1.embedded.html.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{% +highlight +(python)( +linenos)? +%\}\n</string>
			<key>end</key>
			<string>\{% +endhighlight +%\}\n</string>
			<key>name</key>
			<string>source.$1.embedded.html.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{% +(highlight) +(html)( +(linenos))? +%\})\n</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.liquid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.highlight.liquid</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute.language</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute.other</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.$2.embedded.html.markdown</string>
			<key>end</key>
			<string>(\{% +(endhighlight) +%\})\n</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.markdown</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.markdown.jekyll</string>
	<key>uuid</key>
	<string>95B0B966-4F18-4477-8DA3-0366235541ED</string>
</dict>
</plist>
